##
## EPITECH PROJECT, 2019
## Makefile
## File description:
## Makefile
##

all: libmy

libmy:
	@$(MAKE) -C lib/my

clean:
	@$(MAKE) clean -C lib/my

fclean: clean
	@$(RM) libmy.a
	@$(MAKE) fclean -C lib/my

re: fclean all
